name: Practice
author: kidcoben
version: 1.0.0
main: net.syphlex.practice.Practice

commands:
  practice:
  arena:
    aliases: [map]
  party:
    aliases: [p]
  spectate:
    aliases: [spec]
  spawn:
    aliases: [leave]
  build:
  duel:
    aliases: [d]
  event:
    aliases: [e, tournament, tournaments, events]
  inventory: